spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/super_cinema_db?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true"
    password: Albert.nustiu.2002
    username: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
